### ISSUE TITLE
Role has namespace conflicts with standard modules: "setup" and "service"

### ISSUE THREAD

**Issue by karlmdavis** [L-P/ansible-role-acmetool#5]
Please see https://github.com/ansible/ansible/issues/20702 for a detailed explanation of the problem.

Two of this role's `tasks/` files: `tasks/setup.yml` and `tasks/service.yml` conflict with the builtin Ansible modules of the same names. Not sure why this only now started happening for me (since I've been using the role for a while), but this role is now causing all of my plays to fail. Maybe my move to Ansible 2.4.1.0? Not sure.

Renaming the two files (and updating `main.yml` to reflect that, of course) resolves the problem.

**Comment by L-P** [comment]
I'll trust you on this one, I'm still on 2.0 and do not have this issue.

**Comment by karlmdavis** [comment]
Thanks!
